import Link from "next/link";
import { Button } from "@/components/ui/button";
import { getAssessments } from "@/actions/interview";
import StatsCards from "./_components/stats-cards";
import PerformanceChart from "./_components/performace-chart";
import QuizList from "./_components/quiz-list";
import {
  Target,
  Brain,
  Zap,
  Mic,
  ArrowRight,
  BookOpen,
} from "lucide-react";

export default async function InterviewPrepPage() {
  const assessments = await getAssessments();

  return (
    <div className="space-y-8">
      {/* Page header */}
      <div className="flex items-center justify-between">
        <h1 className="text-6xl font-bold gradient-title">
          Interview Preparation
        </h1>
      </div>

      {/* ── Interview Simulator highlight card ── */}
      <div className="relative rounded-2xl border bg-card overflow-hidden shadow-xl">
        {/* gradient accent bar */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-primary via-blue-500 to-purple-500" />

        <div className="p-6 sm:p-8 flex flex-col sm:flex-row items-start sm:items-center gap-6">
          {/* Icon */}
          <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center flex-shrink-0">
            <Target className="h-8 w-8 text-primary" />
          </div>

          {/* Copy */}
          <div className="flex-1 space-y-2">
            <div className="flex items-center gap-2 flex-wrap">
              <h2 className="text-2xl font-bold">Interview Simulator</h2>
              <span className="px-2 py-0.5 text-xs rounded-full bg-primary/10 text-primary font-semibold border border-primary/20">
                New
              </span>
            </div>
            <p className="text-muted-foreground leading-relaxed max-w-xl">
              Practice real-world interview questions generated by Gemini AI. Answer by
              typing or speaking — get instant, constructive feedback with score, strengths
              &amp; model answers after every question.
            </p>

            {/* Feature pills */}
            <div className="flex flex-wrap gap-3 pt-1">
              {[
                { icon: Brain, label: "Gemini AI Questions" },
                { icon: Mic,   label: "Voice Input" },
                { icon: Zap,   label: "Per-Answer Feedback" },
              ].map(({ icon: Icon, label }) => (
                <span
                  key={label}
                  className="flex items-center gap-1.5 text-xs text-muted-foreground bg-muted/40 rounded-full px-3 py-1 border border-border/50"
                >
                  <Icon className="h-3.5 w-3.5 text-primary" />
                  {label}
                </span>
              ))}
            </div>
          </div>

          {/* CTA */}
          <Link href="/interview/simulator" className="flex-shrink-0">
            <Button size="lg" className="gap-2 h-11 px-6 w-full sm:w-auto">
              Launch Simulator
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>
      </div>

      {/* ── Existing quiz dashboard ── */}
      <div className="space-y-6">
        <StatsCards assessments={assessments} />
        <PerformanceChart assessments={assessments} />
        <QuizList assessments={assessments} />
      </div>
    </div>
  );
}
